name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: npm install --legacy-peer-deps
      - run: npm run build --if-present

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: ssh into server and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSHHOST}}
          username: ${{secrets.SSHUSERNAME}}
          password: ${{secrets.SSHPASSWORD}}
          port: ${{secrets.SSHPORT}}
          script: echo ${{secrets.SSHPASSWORD}} | sudo -S systemctl restart raspi
